### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by Ryuo1** [paradox00/Flow.Launcher.Plugin.WindowsTerminal#8]
Failed to load at startup. Manually enabling and running with the trigger hotkey results in a crash.

Logs:
https://pastebin.com/wTrU81gz

Crash message:
```
Please open new issue in: https://github.com/paradox00/Flow.Launcher.Plugin.WindowsTerminal/issues
1. upload log file: C:\Users\anshu\scoop\apps\flow-launcher\current\app-1.16.1\UserData\Logs\1.16.1\2023-08-15.txt
2. copy below exception message

Flow Launcher version: 1.16.1
OS Version: 23475.1000
IntPtr Length: 8
x64: True

Python Path: C:\Users\anshu\scoop\apps\python\3.11.3\pythonw.exe
Node Path: 
Date: 08/15/2023 15:31:39
Exception:
Windows Terminal profiles Exception: 
Websites: https://github.com/paradox00/Flow.Launcher.Plugin.WindowsTerminal
Author: Aviv B.D.
Version: 0.0.8
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\anshu\scoop\apps\flow-launcher\current\app-1.16.1\UserData\Plugins\Windows Terminal profiles-0.0.8\main.py", line 12, in <module>
    TerminalPlugin()
  File "C:\Users\anshu\scoop\apps\flow-launcher\current\app-1.16.1\UserData\Plugins\Windows Terminal profiles-0.0.8\plugin\plugin.py", line 19, in __init__
    self.load_settings()
  File "C:\Users\anshu\scoop\apps\flow-launcher\current\app-1.16.1\UserData\Plugins\Windows Terminal profiles-0.0.8\plugin\plugin.py", line 38, in load_settings
    settings = json.load(settings_file)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anshu\scoop\apps\python\3.11.3\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\anshu\scoop\apps\python\3.11.3\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anshu\scoop\apps\python\3.11.3\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anshu\scoop\apps\python\3.11.3\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\anshu\scoop\apps\flow-launcher\current\app-1.16.1\UserData\Plugins\Windows Terminal profiles-0.0.8\main.py", line 12, in <module>
    TerminalPlugin()
  File "C:\Users\anshu\scoop\apps\flow-launcher\current\app-1.16.1\UserData\Plugins\Windows Terminal profiles-0.0.8\plugin\plugin.py", line 19, in __init__
    self.load_settings()
  File "C:\Users\anshu\scoop\apps\flow-launcher\current\app-1.16.1\UserData\Plugins\Windows Terminal profiles-0.0.8\plugin\plugin.py", line 38, in load_settings
    settings = json.load(settings_file)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anshu\scoop\apps\python\3.11.3\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\anshu\scoop\apps\python\3.11.3\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anshu\scoop\apps\python\3.11.3\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anshu\scoop\apps\python\3.11.3\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 849
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 850
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by paradox00** [comment]
Fixed in version 0.0.10.

**Comment by Ryuo1** [comment]
Sorry for the very late reply, I never knew that you had replied.
Also, the issue still persists.
```
Flow Launcher version: 1.16.2
OS Version: 22631.2861
IntPtr Length: 8
x64: True

Python Path: C:\Users\anshu\scoop\apps\python\3.11.3\pythonw.exe
Node Path: 
Date: 01/05/2024 19:24:03
Exception:
Windows Terminal profiles Exception: 
Websites: https://github.com/paradox00/Flow.Launcher.Plugin.WindowsTerminal
Author: Aviv B.D.
Version: 0.0.10
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: failed to read and parse settings from <_io.TextIOWrapper name='C:\\Users\\anshu\\scoop\\persist\\flow-launcher\\UserData\\Settings\\Plugins\\Windows Terminal profiles\\Settings.json' mode='r' encoding='cp1252'>
Traceback (most recent call last):
  File "C:\Users\anshu\scoop\apps\flow-launcher\current\app-1.16.2\UserData\Plugins\Windows Terminal profiles-0.0.10\plugin\plugin.py", line 42, in load_settings
    settings = json.load(settings_file)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anshu\scoop\apps\python\3.11.3\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\anshu\scoop\apps\python\3.11.3\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anshu\scoop\apps\python\3.11.3\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anshu\scoop\apps\python\3.11.3\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

 ---> System.IO.InvalidDataException: failed to read and parse settings from <_io.TextIOWrapper name='C:\\Users\\anshu\\scoop\\persist\\flow-launcher\\UserData\\Settings\\Plugins\\Windows Terminal profiles\\Settings.json' mode='r' encoding='cp1252'>
Traceback (most recent call last):
  File "C:\Users\anshu\scoop\apps\flow-launcher\current\app-1.16.2\UserData\Plugins\Windows Terminal profiles-0.0.10\plugin\plugin.py", line 42, in load_settings
    settings = json.load(settings_file)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anshu\scoop\apps\python\3.11.3\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\anshu\scoop\apps\python\3.11.3\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anshu\scoop\apps\python\3.11.3\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anshu\scoop\apps\python\3.11.3\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 193
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 849
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 813
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
Logs: https://pastebin.com/k1XbykYk
